### ISSUE TITLE
Add to calendar

### ISSUE THREAD

**Issue by richrout** [cyung/optc#3]
Hey,
I was thinking of doing an add to calendar feature.
Could do a calendar and a calendar feed.

Thoughts? Any objections to me creating a pull request for this?

**Comment by cyung** [comment]
Sure. I've actually been wanting to do that for awhile, but I'm a bit lost on how to design it so that it'll play nice with a mobile layout since 50% of the users are browsing from their phone.

Before you do a pull request, I need to finish testing out the code and push a new update since I refactored it to move all the logic from the controller & directive to a service. I'll have that done in a couple hours.

**Comment by richrout** [comment]
Sounds good. I'll make sure I test on mobile resolution too.

**Comment by cyung** [comment]
I finished refactoring and pushed the code. I put the code in new files since I didn't want to replace the old code in case it broke anything. The files are
- ttime-beta.html
- app/controllers/turtleBetaCtrl.js
- app/services/turtleFact.js
- app/directives/turtleBetaDirective.js

Let me know if you have any questions.

**Comment by richrout** [comment]
I did notice the beta times were different to the non-beta times. Was that intentional or a bug in the time calculations?

**Comment by cyung** [comment]
I forgot to set it to display in the local time zone. I didn't catch that bug since I was testing it with my time zone set to Japan. It's fixed now.
